### ISSUE TITLE
No Price Graph on Unity Asset Store

### ISSUE THREAD

**Issue by patrickmaher** [DespairServices/asset-store-price-tracker#1]
The Chrome Web Store link says "This item is not available".
I am using version 2.1.1 downloaded from GitHub. The price graph does not display on Unity asset store pages and the following error is logged in the Chrome developer console.

Uncaught (in promise) Error: Error 2000
    at content-script-unity.js:2:3628
    at Generator.next (<anonymous>)
    at a (content-script-unity.js:2:2035)

**Comment by RampantDespair** [comment]
@patrickmaher 
Apologies for the late reply, but I am currently in the process of moving everything.
I will let you know once everything is back up and running.

**Comment by RampantDespair** [comment]
@patrickmaher 
Happy to announce that everything works again and added more browser support.
